//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequerimientoAsignado
    {
        public int ID_RequerimientoAsignado { get; set; }
        public int ID_ingreso_requerimiento { get; set; }
        public Nullable<int> ID_Solicitante { get; set; }
        public string Requerimiento { get; set; }
        public Nullable<System.DateTime> F_revision { get; set; }
        public string Comentario_rev { get; set; }
        public Nullable<decimal> Duracion_Hr { get; set; }
        public Nullable<int> ID_Ejecutor { get; set; }
        public string Comentario_asig { get; set; }
        public Nullable<decimal> Cumplimiento { get; set; }
        public Nullable<System.DateTime> F_inicio { get; set; }
        public Nullable<System.DateTime> F_fin { get; set; }
        public Nullable<int> ID_Publicado { get; set; }
        public Nullable<int> ID_Estado { get; set; }
    }
}
