//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revision_requerimiento
    {
        public int Ingreso_requerimiento_id { get; set; }
        public Nullable<System.DateTime> F_revision { get; set; }
        public string Comentario_rev { get; set; }
        public Nullable<int> Duracion_Hr { get; set; }
        public string Ejecutor { get; set; }
    }
}
