//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdUsuario
    {
        public string CCiUsuario { get; set; }
        public string CCiDocumento { get; set; }
        public string CDsNombre { get; set; }
        public string CDsApellido { get; set; }
        public string CSNPerfil { get; set; }
        public string CSNAccesoAdm { get; set; }
        public string CCiDepartamento { get; set; }
        public string CDsDepartamento { get; set; }
        public string CCiCargo { get; set; }
        public string CDsCargo { get; set; }
        public string CTxClave { get; set; }
        public string CTxEmail { get; set; }
        public string CCeUsuario { get; set; }
        public string CCtUsuario { get; set; }
        public string CCiDominio { get; set; }
        public string CCiUsuarioDominio { get; set; }
        public string CCiRol { get; set; }
        public string CSNPideClave { get; set; }
        public string CSnUserSAP { get; set; }
        public string CCiUserSAP { get; set; }
        public string CTxClaveSAP { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public System.DateTime DFiIngreso { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public Nullable<System.DateTime> DFmModifica { get; set; }
    }
}
