//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZPLA_VIEW_GENITX_AREA_DPTO
    {
        public short empcod { get; set; }
        public string GprCod { get; set; }
        public string GprCtaCod { get; set; }
        public string GprDsc { get; set; }
        public string GprEstado { get; set; }
        public string GprCorreos { get; set; }
        public string DgprCod { get; set; }
        public string DgprCtaCod { get; set; }
        public string DgprDsc { get; set; }
        public string GctaCod { get; set; }
        public string SgrpCtaCod { get; set; }
        public string DgprCorreo { get; set; }
        public string DgprCC { get; set; }
    }
}
