//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZPLA_DETA_GENTIX_EMPLEADOS
    {
        public int CtrNro { get; set; }
        public string PrsCod { get; set; }
        public string CtrGprCod { get; set; }
        public string CtrDgprCod { get; set; }
        public string CDsNombresEmpleado { get; set; }
        public string CDsApellidosEmpleado { get; set; }
        public string CDsEmpleado { get; set; }
        public string PrsPriNombre { get; set; }
        public string PrsSegNombre { get; set; }
        public string PrsPatApellido { get; set; }
        public string PrsMatApellido { get; set; }
        public Nullable<int> CtrCargCod { get; set; }
        public string CargNom { get; set; }
        public string CtrEstado { get; set; }
        public string CCiArea { get; set; }
        public string CDsArea { get; set; }
        public string CCiDpto { get; set; }
        public string CDsDpto { get; set; }
    }
}
