//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZPLA_DETA_OPCIONES
    {
        public string CCiAplicacion { get; set; }
        public string CDsAplicacion { get; set; }
        public decimal NNuIdFuncion { get; set; }
        public string CCiFuncion { get; set; }
        public string CDsFuncion { get; set; }
        public decimal NNuIdOpcion { get; set; }
        public string CDsOpcionMenu { get; set; }
        public string CDsOpcionPadre { get; set; }
        public decimal NNuNivel { get; set; }
        public string CDsNivel { get; set; }
        public decimal NNuPosicion { get; set; }
        public decimal NNuIdOpcionPadre { get; set; }
        public string CSNUltimoNivel { get; set; }
        public string CSNSeparador { get; set; }
        public string CCtClase { get; set; }
        public string CDsArchivo { get; set; }
        public string CDsController { get; set; }
        public string CDsEventoController { get; set; }
        public string CDsImagen { get; set; }
        public string CDsArgumento { get; set; }
        public string cciAplicacionOrigen { get; set; }
        public string CSNOcultaOpcion { get; set; }
        public string CSNGrupo { get; set; }
        public string CDsAbreviaturaMenu { get; set; }
    }
}
